### ISSUE TITLE
Config File overwritten on startup

### ISSUE THREAD

**Issue by robertlynch3** [ruimarinho/docker-openvpn-monitor#27]
The docker building is overwriting the mounted config file.

```yml
version: '3'
services:
    openvpn-monitor:
      image: ruimarinho/openvpn-monitor
      volumes:
        - ./openvpn-monitor.conf:/openvpn-monitor/openvpn-monitor.conf
      ports:
        - 127.0.0.1:9000:80
````
Prior to startup, my config file look like 
```
cat openvpn-monitor.conf
[OpenVPN-Monitor]
geoip_data=/var/lib/GeoIP/GeoLite2-City.mmdb
datetime_format=%d/%m/%Y %H:%M:%S
site=VPN
maps=False
maps_height=500

[site 0]
host=192.168.0.1
port=5555
name=site 0
password=abc123
show_disconnect=True

[site 1]
host=192.168.0.2
port=5555
name=site 1
password=abc123
show_disconnect=True

[site 2]
host=192.168.0.3
port=5555
name=site 2
password=abc123
show_disconnect=True
```

After startup my config file looks like 
```
cat openvpn-monitor.conf
[OpenVPN-Monitor]
geoip_data=/var/lib/GeoIP/GeoLite2-City.mmdb
datetime_format=%d/%m/%Y %H:%M:%S
```
